// Checks the plugin you built in plugin/: manifest, layout, one skill, one command. Do not edit this file.
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { nameProblem, validateMarketplace, validatePlugin } from "../scripts/validate-plugin.mjs";

const plugin = validatePlugin();
const market = validateMarketplace();
const problems = (result, code) => result.errors.filter((e) => e.code === code).map((e) => e.message);
const expectClean = (result, code) => assert.deepEqual(problems(result, code), [], `\n  ${problems(result, code).join("\n  ")}\n`);

test("the manifest exists at .claude-plugin/plugin.json with a name, version, description and author", () => expectClean(plugin, "manifest"));
test("only plugin.json is inside .claude-plugin/, and no CLAUDE.md sits at the plugin root", () => expectClean(plugin, "layout"));
test("the plugin has one skill: skills/pr-description/SKILL.md with a Use when description", () => expectClean(plugin, "skill"));
test("the plugin has one command: commands/changelog.md with a description and $ARGUMENTS", () => expectClean(plugin, "command"));
test("hooks, if you added any, are in hooks/hooks.json with a top-level hooks key", () => expectClean(plugin, "hooks"));
test("the marketplace.json, if you added one, is valid and its entry matches the plugin", () => {
  assert.deepEqual(market.errors.map((e) => e.message), [], "\n  " + market.errors.map((e) => e.message).join("\n  ") + "\n");
});

// The validator itself: these must hold whatever you build.
test("validator: reserved and badly formed plugin names are rejected", () => {
  assert.ok(nameProblem("claude-helper", "x"));
  assert.ok(nameProblem("anthropic", "x"));
  assert.ok(nameProblem("My Plugin", "x"));
  assert.equal(nameProblem("fm-team-kit", "x"), null);
});
test("validator: components inside .claude-plugin/ are flagged because they do not load", () => {
  const dir = mkdtempSync(join(tmpdir(), "ex46-"));
  mkdirSync(join(dir, ".claude-plugin", "skills", "x"), { recursive: true });
  writeFileSync(join(dir, ".claude-plugin", "plugin.json"), JSON.stringify({ name: "fm-team-kit" }));
  const res = validatePlugin(dir);
  assert.ok(problems(res, "layout").some((m) => m.includes(".claude-plugin/skills")));
});
