// Checks the automation you built: a format-on-edit hook, a route-scaffolding skill,
// and the route that skill produced. Do not edit this file.
import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (rel) => readFileSync(join(root, rel), "utf8");
const MESSY = "const a = 1;   \r\n\tconst b = 2;\n\n\n\nexport { a, b };";
const CLEAN = "const a = 1;\n  const b = 2;\n\nexport { a, b };\n";

function runHook(payload) {
  const script = join(root, "scripts/hook-format.mjs");
  assert.ok(existsSync(script), "scripts/hook-format.mjs is missing: the hook needs a script that reads the hook JSON from stdin");
  return spawnSync(process.execPath, [script], { input: JSON.stringify(payload), encoding: "utf8", cwd: root });
}

// ---- 1. The hook script handles both tools' payload shapes -------------------------------

test("hook script formats the file named in a Claude Code Edit/Write payload", () => {
  const dir = mkdtempSync(join(tmpdir(), "ex44-"));
  const file = join(dir, "a.js");
  writeFileSync(file, MESSY);
  const res = runHook({ hook_event_name: "PostToolUse", tool_name: "Write", tool_input: { file_path: file }, cwd: dir });
  assert.equal(res.status, 0, res.stderr);
  assert.equal(readFileSync(file, "utf8"), CLEAN);
});

test("hook script formats files named in a Codex apply_patch payload (relative paths, cwd)", () => {
  const dir = mkdtempSync(join(tmpdir(), "ex44-"));
  writeFileSync(join(dir, "b.js"), MESSY);
  writeFileSync(join(dir, "c.md"), "# Title   \n\n\n\ntext");
  const patch = [
    "*** Begin Patch",
    "*** Update File: b.js",
    "@@",
    "-x",
    "+y",
    "*** Add File: c.md",
    "+# Title",
    "*** Delete File: gone.js",
    "*** End Patch",
  ].join("\n");
  const res = runHook({ hook_event_name: "PostToolUse", tool_name: "apply_patch", tool_input: { command: patch }, cwd: dir });
  assert.equal(res.status, 0, res.stderr);
  assert.equal(readFileSync(join(dir, "b.js"), "utf8"), CLEAN);
  assert.equal(readFileSync(join(dir, "c.md"), "utf8"), "# Title\n\ntext\n");
});

test("hook script ignores unrelated tools, unknown file types and missing files without failing", () => {
  const dir = mkdtempSync(join(tmpdir(), "ex44-"));
  const png = join(dir, "logo.png");
  writeFileSync(png, "not really a png   \n\n\n");
  for (const payload of [
    { hook_event_name: "PostToolUse", tool_name: "Bash", tool_input: { command: "echo hi" }, cwd: dir },
    { hook_event_name: "PostToolUse", tool_name: "Write", tool_input: { file_path: png }, cwd: dir },
    { hook_event_name: "PostToolUse", tool_name: "Write", tool_input: { file_path: join(dir, "missing.js") }, cwd: dir },
  ]) {
    const res = runHook(payload);
    assert.equal(res.status, 0, res.stderr);
  }
  assert.equal(readFileSync(png, "utf8"), "not really a png   \n\n\n");
});

// ---- 2. The hook is wired up in at least one tool's config -------------------------------

function claudeHookWired() {
  const rel = ".claude/settings.json";
  if (!existsSync(join(root, rel))) return `${rel} is missing`;
  let settings;
  try {
    settings = JSON.parse(read(rel));
  } catch {
    return `${rel} is not valid JSON`;
  }
  const groups = settings?.hooks?.PostToolUse;
  if (!Array.isArray(groups)) return `${rel} has no hooks.PostToolUse array`;
  const ok = groups.some(
    (g) =>
      /Edit/.test(g.matcher ?? "") &&
      /Write/.test(g.matcher ?? "") &&
      (g.hooks ?? []).some((h) => h.type === "command" && /hook-format/.test(h.command ?? "")),
  );
  return ok ? null : `${rel}: no PostToolUse group with a matcher covering Edit and Write that runs hook-format`;
}

function codexHookWired() {
  if (existsSync(join(root, ".codex/hooks.json"))) {
    let hooks;
    try {
      hooks = JSON.parse(read(".codex/hooks.json"));
    } catch {
      return ".codex/hooks.json is not valid JSON";
    }
    const groups = hooks?.hooks?.PostToolUse;
    if (!Array.isArray(groups)) return ".codex/hooks.json has no hooks.PostToolUse array";
    const ok = groups.some(
      (g) => /apply_patch|Edit|Write/.test(g.matcher ?? "") && (g.hooks ?? []).some((h) => h.type === "command" && /hook-format/.test(h.command ?? "")),
    );
    return ok ? null : ".codex/hooks.json: no PostToolUse group matching apply_patch (or Edit/Write) that runs hook-format";
  }
  if (existsSync(join(root, ".codex/config.toml"))) {
    const toml = read(".codex/config.toml");
    return /\[\[hooks\.PostToolUse\]\]/.test(toml) && /hook-format/.test(toml) && /apply_patch|Edit|Write/.test(toml)
      ? null
      : ".codex/config.toml: no [[hooks.PostToolUse]] entry matching apply_patch that runs hook-format";
  }
  return ".codex/hooks.json (or .codex/config.toml) is missing";
}

test("a format-on-edit hook is configured (Claude Code or Codex)", () => {
  const claude = claudeHookWired();
  const codex = codexHookWired();
  if (claude === null || codex === null) return;
  assert.fail(`Wire the hook in at least one tool.\n  Claude Code: ${claude}\n  Codex: ${codex}`);
});

// ---- 3. The scaffolding skill exists and points at the conventions -----------------------

function skillProblems(dir) {
  const rel = `${dir}/new-api-route/SKILL.md`;
  if (!existsSync(join(root, rel))) return [`${rel} is missing`];
  const m = read(rel).replace(/\r\n/g, "\n").match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) return [`${rel} has no YAML frontmatter`];
  const [, front, body] = m;
  const problems = [];
  const name = front.match(/^name:\s*(.+)$/m)?.[1]?.trim();
  const description = front.match(/^description:\s*(.+)$/m)?.[1]?.trim();
  if (name !== "new-api-route") problems.push(`${rel}: name must be "new-api-route" (match the folder)`);
  if (!description || description.length < 60) problems.push(`${rel}: description needs 60+ characters saying what it does and when to use it`);
  else if (!/route/i.test(description)) problems.push(`${rel}: description should mention "route"`);
  if (!/CONVENTIONS\.md|src\/routes\/health\.js/.test(body)) problems.push(`${rel}: body should point at CONVENTIONS.md or the example route`);
  if (!/src\/routes\/index\.js/.test(body)) problems.push(`${rel}: body should tell the agent to register the route in src/routes/index.js`);
  if (!/tests\/routes/.test(body)) problems.push(`${rel}: body should tell the agent to add a test under tests/routes/`);
  return problems;
}

test("a new-api-route skill exists (Claude Code or Codex location)", () => {
  const claude = skillProblems(".claude/skills");
  const codex = skillProblems(".agents/skills");
  if (claude.length === 0 || codex.length === 0) return;
  assert.fail(`Create the skill in at least one tool's location.\n  .claude/skills: ${claude.join("; ")}\n  .agents/skills: ${codex.join("; ")}`);
});

// ---- 4. The skill was used: an "orders" route follows the conventions ---------------------

test("the orders route exists, is registered alphabetically, and follows the conventions", async () => {
  assert.ok(existsSync(join(root, "src/routes/orders.js")), "src/routes/orders.js is missing: run the skill to scaffold an orders route");
  const { routes } = await import("../src/routes/index.js");
  const paths = routes.map((r) => r.path);
  assert.ok(paths.includes("/orders"), "orders is not registered in src/routes/index.js");
  assert.deepEqual(paths, [...paths].sort(), "routes in src/routes/index.js must stay alphabetical");
  const source = read("src/routes/orders.js");
  assert.match(source, /from "\.\.\/http\.js"/, "orders.js must build responses with ../http.js");
  const orders = routes.find((r) => r.path === "/orders");
  assert.equal(typeof orders.handler, "function");
  const bad = await orders.handler({ method: "GET", query: {} });
  assert.equal(bad.status, 400, "orders with no input must return badRequest (400)");
  const good = await orders.handler({ method: "GET", query: { customer: "c-1" } });
  assert.equal(good.status, 200);
  assert.ok(Array.isArray(good.body), "orders for a customer returns an array");
  assert.ok(existsSync(join(root, "tests/routes/orders.test.js")), "tests/routes/orders.test.js is missing");
});

test("every registered route follows the base conventions", async () => {
  const { routes } = await import("../src/routes/index.js");
  for (const r of routes) {
    assert.match(r.path, /^\/[a-z]+$/, `${r.path}: path must be "/<lowercase name>"`);
    assert.equal(typeof r.handler, "function", `${r.path}: handler must be a function`);
    const res = await r.handler({ method: "GET", query: {} });
    assert.equal(typeof res.status, "number", `${r.path}: handler must return an http.js response`);
  }
});
