// Verifies the routing config. Do not edit this file.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (rel) => readFileSync(path.join(root, rel), "utf8");

const EFFORT = ["low", "medium", "high", "xhigh", "max"];
const STRONG_CLAUDE = ["opus", "claude-opus-5-5"];
const FAST_CLAUDE = ["sonnet", "haiku", "claude-sonnet-5-5"];

/** Frontmatter of a Claude Code subagent file: key: value lines between --- fences. */
function frontmatter(rel) {
  const m = read(rel).match(/^---\r?\n([\s\S]*?)\r?\n---/);
  assert.ok(m, `${rel} needs YAML frontmatter between --- fences`);
  const out = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z]+):\s*(.*)$/);
    if (kv) out[kv[1]] = kv[2].trim();
  }
  return out;
}

/** Single-line `key = "value"` pairs from a Codex TOML file. Enough for this exercise. */
function toml(rel) {
  const out = {};
  for (const line of read(rel).split(/\r?\n/)) {
    const kv = line.match(/^([a-z_]+)\s*=\s*"([^"\n]*)"\s*(#.*)?$/);
    if (kv) out[kv[1]] = kv[2];
  }
  return out;
}

const tools = (fm) =>
  (fm.tools ?? "")
    .split(",")
    .map((t) => t.trim())
    .filter(Boolean);

test("Claude Code: default model routes plan mode to Opus and execution to Sonnet", () => {
  const settings = JSON.parse(read(".claude/settings.json"));
  assert.equal(settings.model, "opusplan");
});

test("Claude Code: reviewer subagent uses the strong model and is read-only", () => {
  const fm = frontmatter(".claude/agents/reviewer.md");
  assert.equal(fm.name, "reviewer");
  assert.ok(STRONG_CLAUDE.includes(fm.model), `reviewer model must be one of ${STRONG_CLAUDE}, got "${fm.model}"`);
  const t = tools(fm);
  assert.ok(t.length > 0, "reviewer must list an explicit tools allowlist");
  for (const banned of ["Edit", "Write", "MultiEdit", "NotebookEdit"]) {
    assert.ok(!t.includes(banned), `reviewer must not have ${banned}`);
  }
});

test("Claude Code: implementer subagent uses a fast model and can edit", () => {
  const fm = frontmatter(".claude/agents/implementer.md");
  assert.equal(fm.name, "implementer");
  assert.ok(FAST_CLAUDE.includes(fm.model), `implementer model must be one of ${FAST_CLAUDE}, got "${fm.model}"`);
  assert.ok(tools(fm).includes("Edit"), "implementer needs the Edit tool");
});

test("Codex: plan profile is read-only and thinks harder than the implementation profile", () => {
  const plan = toml("codex/fm-plan.config.toml");
  const impl = toml("codex/fm-impl.config.toml");
  for (const [name, p] of [
    ["fm-plan", plan],
    ["fm-impl", impl],
  ]) {
    assert.ok(p.model, `${name}: model is required`);
    assert.ok(EFFORT.includes(p.model_reasoning_effort), `${name}: model_reasoning_effort must be one of ${EFFORT}`);
  }
  assert.equal(plan.sandbox_mode, "read-only");
  assert.equal(impl.sandbox_mode, "workspace-write");
  assert.ok(
    EFFORT.indexOf(plan.model_reasoning_effort) > EFFORT.indexOf(impl.model_reasoning_effort),
    "plan effort must be higher than implementation effort",
  );
});

test("Codex: project reviewer agent is read-only with high reasoning", () => {
  const a = toml(".codex/agents/reviewer.toml");
  assert.equal(a.name, "reviewer");
  assert.ok(a.description, "description is required");
  assert.ok(read(".codex/agents/reviewer.toml").includes("developer_instructions"), "developer_instructions is required");
  assert.ok(a.model, "model is required");
  assert.equal(a.sandbox_mode, "read-only");
  assert.ok(EFFORT.indexOf(a.model_reasoning_effort) >= EFFORT.indexOf("high"), "reviewer effort must be high or above");
  const impl = toml("codex/fm-impl.config.toml");
  assert.ok(
    EFFORT.indexOf(a.model_reasoning_effort) > EFFORT.indexOf(impl.model_reasoning_effort),
    "reviewer should think harder than the implementation profile",
  );
});

test("timings.md records one measured run per phase per tool", () => {
  assert.ok(existsSync(path.join(root, "timings.md")), "timings.md is missing");
  const text = read("timings.md");
  const rows = text
    .split(/\r?\n/)
    .filter((l) => l.startsWith("|"))
    .map((l) =>
      l
        .split("|")
        .slice(1, -1)
        .map((c) => c.trim()),
    )
    .filter((c) => c.length >= 5 && !/^-+$/.test(c[0]) && c[0].toLowerCase() !== "phase");
  const seen = new Set();
  for (const [phase, tool, model, effort, seconds] of rows) {
    assert.ok(["plan", "implement", "review"].includes(phase), `unknown phase "${phase}"`);
    assert.ok(["claude", "codex"].includes(tool), `unknown tool "${tool}"`);
    assert.ok(model.length > 0 && !model.includes("<"), `row ${phase}/${tool}: fill in the model`);
    assert.ok(EFFORT.includes(effort), `row ${phase}/${tool}: effort must be one of ${EFFORT}`);
    assert.ok(Number(seconds) > 0, `row ${phase}/${tool}: seconds must be a positive number`);
    seen.add(`${phase}/${tool}`);
  }
  for (const phase of ["plan", "implement", "review"]) {
    for (const tool of ["claude", "codex"]) {
      assert.ok(seen.has(`${phase}/${tool}`), `missing row ${phase}/${tool}`);
    }
  }
  const decision = text.split(/^## Decision/m)[1] ?? "";
  assert.ok(decision.trim().length >= 40, "write a Decision paragraph (40+ chars): was the fast model good enough to implement?");
});
