// Checks that you defined a test-runner and a reviewer subagent, in Claude Code format,
// Codex format, or both. Do not edit this file.
import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (rel) => readFileSync(join(root, rel), "utf8");

function claudeAgent(name) {
  const rel = `.claude/agents/${name}.md`;
  if (!existsSync(join(root, rel))) return { error: `${rel} is missing` };
  const m = read(rel)
    .replace(/\r\n/g, "\n")
    .match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) return { error: `${rel} has no YAML frontmatter` };
  const [, front, body] = m;
  const field = (key) => {
    const lines = front.split("\n");
    const i = lines.findIndex((l) => l.startsWith(`${key}:`));
    if (i === -1) return null;
    let value = lines[i].slice(key.length + 1);
    // Continuation lines: a YAML list ("  - Read") or an indented wrapped value.
    for (let j = i + 1; j < lines.length && /^\s+\S/.test(lines[j]); j++) value += " " + lines[j];
    return value.trim();
  };
  return {
    rel,
    name: field("name"),
    description: field("description"),
    tools: field("tools"),
    model: field("model"),
    body: body.trim(),
  };
}

function codexAgent(name) {
  const rel = `.codex/agents/${name}.toml`;
  if (!existsSync(join(root, rel))) return { error: `${rel} is missing` };
  const text = read(rel).replace(/\r\n/g, "\n");
  const str = (key) => {
    const triple = text.match(new RegExp(`^${key}\\s*=\\s*"""([\\s\\S]*?)"""`, "m"));
    if (triple) return triple[1].trim();
    const single = text.match(new RegExp(`^${key}\\s*=\\s*"([^"\\n]*)"`, "m"));
    return single ? single[1].trim() : null;
  };
  return {
    rel,
    name: str("name"),
    description: str("description"),
    instructions: str("developer_instructions"),
    sandbox: str("sandbox_mode"),
  };
}

function claudeProblems() {
  const problems = [];
  for (const name of ["test-runner", "reviewer"]) {
    const a = claudeAgent(name);
    if (a.error) {
      problems.push(a.error);
      continue;
    }
    if (a.name !== name) problems.push(`${a.rel}: name must be "${name}"`);
    if (!a.description || a.description.length < 20) problems.push(`${a.rel}: description must say when to delegate (20+ chars)`);
    if (!a.body || a.body.length < 40) problems.push(`${a.rel}: the system prompt body is too short`);
    if (!a.tools) {
      problems.push(`${a.rel}: set an explicit tools list (omitting it inherits every tool)`);
    } else {
      const tools = a.tools.split(/[\s,-]+/).filter(Boolean);
      if (tools.some((t) => t === "Edit" || t === "Write")) problems.push(`${a.rel}: ${name} must not have Edit or Write`);
      if (name === "test-runner" && !tools.includes("Bash")) problems.push(`${a.rel}: test-runner needs Bash to run tests`);
      if (name === "reviewer" && !tools.includes("Read")) problems.push(`${a.rel}: reviewer needs Read`);
    }
    if (name === "reviewer" && !a.model) problems.push(`${a.rel}: set a model for the reviewer`);
  }
  return problems;
}

function codexProblems() {
  const problems = [];
  for (const name of ["test-runner", "reviewer"]) {
    const a = codexAgent(name);
    if (a.error) {
      problems.push(a.error);
      continue;
    }
    if (a.name !== name) problems.push(`${a.rel}: name must be "${name}"`);
    if (!a.description || a.description.length < 20) problems.push(`${a.rel}: description must say when to delegate (20+ chars)`);
    if (!a.instructions || a.instructions.length < 40) problems.push(`${a.rel}: developer_instructions is missing or too short`);
    if (name === "reviewer" && a.sandbox !== "read-only") problems.push(`${a.rel}: reviewer must set sandbox_mode = "read-only"`);
  }
  return problems;
}

test("test-runner and reviewer subagents are defined (Claude Code or Codex format)", () => {
  const claude = claudeProblems();
  const codex = codexProblems();
  if (claude.length === 0 || codex.length === 0) return;
  assert.fail(
    `Define both subagents in at least one tool's format.\n` +
      `Claude Code (.claude/agents/*.md):\n  - ${claude.join("\n  - ")}\n` +
      `Codex (.codex/agents/*.toml):\n  - ${codex.join("\n  - ")}`,
  );
});
