import { z } from "zod";
import { toolVersionsSchema } from "./lesson";

const slug = z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "expected kebab-case slug");
const isoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "expected YYYY-MM-DD");

/**
 * public/media/lessons/<lesson-slug>/<id>.media.json (PRD §15.2). One manifest per item,
 * generated by the render/record scripts. Never edited by hand, never seeded into the DB.
 */
export const mediaManifestSchema = z
  .object({
  id: slug,
  lesson_slug: slug,
  kind: z.enum(["animation", "recording", "tldr"]),
  title: z.string().min(1),
  duration_s: z.number().positive(),
  width: z.number().int().positive(),
  height: z.number().int().positive(),
  /** One key per tool the item depicts. */
  tool_versions: toolVersionsSchema
    .partial()
    .refine((v) => Object.values(v).some(Boolean), "expected at least one tool version"),
  made_on: isoDate,
  model_calls: z.boolean(),
  /** Hash of the steps.json or .tape that produced the item (MD-7). For kind "tldr" see tldrSourceHash (PRD §19.5). */
  source_hash: z.string().min(1),
  /** Template version the TL;DR video was rendered with. Required for kind "tldr", absent otherwise (PRD §19.5). */
  template_version: z.number().int().positive().optional(),
  })
  .refine((m) => (m.kind === "tldr") === (m.template_version !== undefined), {
    path: ["template_version"],
    message: 'template_version is required when kind is "tldr" and absent otherwise',
  });
export type MediaManifest = z.infer<typeof mediaManifestSchema>;

/** Size caps (MD-6), in bytes. */
export const MEDIA_CAPS = {
  mp4: 4 * 1024 * 1024,
  poster: 60 * 1024,
  total: 20 * 1024 * 1024,
} as const;

/** Tighter caps for kind "tldr" (PRD §19.6, TL-13), in bytes. */
export const TLDR_MEDIA_CAPS = {
  mp4: 400 * 1024,
  poster: 30 * 1024,
} as const;
