// Static checks for the three visual bugs, plus proof that you reproduced them (REPRO.md).
// A browser would be the real check; these keep verification deterministic and dependency-free.
// Do not edit this file.
import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const css = readFileSync(join(root, "app/pricing.module.css"), "utf8").replace(/\/\*[\s\S]*?\*\//g, "");

function rule(selector) {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const m = css.match(new RegExp(`(?:^|\\})\\s*${escaped}\\s*\\{([^}]*)\\}`));
  assert.ok(m, `no top-level rule for ${selector} in app/pricing.module.css`);
  return m[1];
}

test("the plan grid does not force fixed-width columns", () => {
  const body = rule(".grid");
  assert.doesNotMatch(body, /repeat\(\s*\d+\s*,\s*\d+px\s*\)/, "grid-template-columns still uses N fixed-px columns");
  assert.match(body, /grid-template-columns:[^;]*(auto-fit|auto-fill|minmax\(|1fr)/, "grid-template-columns must be flexible (auto-fit, minmax or fr)");
});

test("the price is not clipped", () => {
  const body = rule(".price");
  assert.doesNotMatch(body, /overflow:\s*hidden/, ".price still has overflow: hidden");
  assert.doesNotMatch(body, /(^|[;\s])width:\s*\d+px/, ".price still has a fixed pixel width");
});

test("the call to action is a usable tap target", () => {
  const body = rule(".cta");
  const m = body.match(/min-height:\s*(\d+)px/);
  assert.ok(m, ".cta needs a min-height in px");
  assert.ok(Number(m[1]) >= 44, `.cta min-height is ${m[1]}px, expected at least 44px`);
});

test("the page still uses the styled classes", () => {
  const page = readFileSync(join(root, "app/page.jsx"), "utf8");
  for (const cls of ["grid", "price", "cta"]) assert.ok(page.includes(`styles.${cls}`), `app/page.jsx no longer uses styles.${cls}`);
});

test("REPRO.md documents the reproduction you did in a browser", () => {
  const path = join(root, "REPRO.md");
  assert.ok(existsSync(path), "REPRO.md is missing: write down what you saw in the browser before fixing");
  const text = readFileSync(path, "utf8");
  assert.ok(text.trim().length >= 200, "REPRO.md is too short to be a real reproduction (200+ characters)");
  assert.match(text, /375/, "REPRO.md should name the narrow viewport you tested (for example 375px)");
  assert.match(text, /(scrollWidth|overflow|clipped|truncat|horizontal scroll)/i, "REPRO.md should describe the symptom you observed");
});
