// Checks that the release-notes skill can actually be discovered and triggered. Do not edit this file.
import { test } from "node:test";
import assert from "node:assert/strict";
import { parseFrontmatter } from "../scripts/frontmatter.mjs";
import { checkSkills } from "../scripts/check-skills.mjs";

const result = checkSkills();
const problems = (code) => result.errors.filter((e) => e.code === code).map((e) => e.message);
const expectClean = (code) => assert.deepEqual(problems(code), [], `\n  ${problems(code).join("\n  ")}\n`);

test("the skill lives in a documented location, as <name>/SKILL.md", () => expectClean("location"));
test("the skill folder and name follow the convention", () => expectClean("name"));
test("the frontmatter parses (a broken block loads the skill with no metadata)", () => expectClean("frontmatter"));
test("the description says what the skill does and when to use it", () => expectClean("description"));
test("the description matches the requests it should handle and not the ones it should not", () => expectClean("triggers"));
test("nothing stops the model from loading the skill on its own", () => expectClean("invocation"));
test("supporting files sit beside SKILL.md and are referenced from it", () => expectClean("supporting"));

// The strict frontmatter reader catches the mistakes this exercise is built around.
test("frontmatter: a quote inside a quoted value is rejected, the other quote character is fine", () => {
  assert.equal(parseFrontmatter('---\nname: a\ndescription: "Draft "release notes" now"\n---\nbody').ok, false);
  const ok = parseFrontmatter('---\nname: a\ndescription: \'Draft "release notes" now\'\n---\nbody');
  assert.equal(ok.ok, true);
  assert.equal(ok.data.description, 'Draft "release notes" now');
});
test("frontmatter: an unclosed quote is rejected", () => {
  assert.equal(parseFrontmatter('---\nname: a\ndescription: "Draft release notes\n---\nbody').ok, false);
});
test("frontmatter: the opening --- must be the first line", () => {
  assert.equal(parseFrontmatter("\n---\nname: a\n---\n").ok, false);
});
